# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set variables
        run: NAME=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)
             TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      - name: Set variables
        run: echo "$NAME"
      - name: Maven Package
        #run: mvn -B clean package -DskipTests -Pprod
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        #run: mvn -B clean verify -Pprod
        run: mvn -B -DskipTests org.springframework.boot:spring-boot-maven-plugin:build-image

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: "${{ secrets.DOCKER_USER }}/${NAME}:${TAG}"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
  #    - name: Build Docker image
  #      run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO

  #redeploy:
  #  name: Redeploy webhook call
  #  runs-on: ubuntu-latest
  #  needs: [docker]
  #  steps:
  #    - name: Deploy docker container webhook
  #      uses: joelwmale/webhook-action@master
  #      env:
  #        WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          #data: "{ 'myField': 'myFieldValue'}"